version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule: 
      interval: daily
    groups:
      dependencies:
        patterns:
          - '*'
    cooldown:
      default-days: 7
